# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 21:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('answered_date', models.DateTimeField()),
                ('answer_again_from', models.DateTimeField()),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question to ask as a text string', max_length=2048)),
                ('answers', jsonfield.fields.JSONField(default={}, help_text='The possible answers stored in a json field')),
                ('pause_seconds', models.IntegerField(default=604800, help_text='Number of seconds until asking this question again', validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=False, help_text='Whether the question is actively being asked or not')),
            ],
        ),
        migrations.AddField(
            model_name='weeklyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WeeklyQuestion'),
        ),
    ]
